src/vulkan-renderer/thread-pool/InexorThreadPool.hpp
PS. there are some spelling mistakes in the documentation and comments.
=> Prevent possible data race in InexorThreadPool

.gitignore
I also added
`cmake-build-*` which uses CLion as building folders
=> Update gitignore with rudimentary c++ rules

.travis.yml
=> Use Ninja build generator on travis

CMakeLists.txt, cmake/conan_setup.cmake
Should i squash everything after the review?
---
Adds a new cmake option
`INEXOR_CONAN_PROFILE` to change the conan profile to use. Default is `default`.
example
> cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja -DINEXOR_CONAN_PROFILE=default_mingw ./
=> Yet another Cmake refactoring

BUILDING.md
Update BUILDING.md with instructions for building on gentoo linux.
=> Add build instructions for gentoo

benchmarks/engine_benchmark_main.cpp, example/main.cpp, tests/unit_tests_main.cpp
=> Tweak logging initiation

.github/workflows/build_cmake.yml
Changes:
- Add VMA off option on linux builds
- Build on pull requests
- Add windows builds
=> [ci] Refactor ci and add windows

.github/workflows/build_cmake.yml
+ other improvements
Close #116
=> [ci] Fix linux build

configuration/renderer.toml, include/inexor/vulkan-renderer/application.hpp, src/vulkan-renderer/application.cpp
This pull request cleans up `Application::load_toml_configuration` by:
- Simplifying the file handling code
- Fixing the typo when setting `window_height`
- Removing unnecessary new lines
=> [code] Cleanup Application::load_toml_configuration

.clang-tidy, include/inexor/vulkan-renderer/debug_callback.hpp, include/inexor/vulkan-renderer/gltf-model/material.hpp, include/inexor/vulkan-renderer/renderer.hpp, include/inexor/vulkan-renderer/settings_decision_maker.hpp, include/inexor/vulkan-renderer/texture.hpp, include/inexor/vulkan-renderer/tools/cla_parser.hpp, src/CMakeLists.txt, src/vulkan-renderer/application.cpp, src/vulkan-renderer/availability_checks.cpp, src/vulkan-renderer/camera.cpp, src/vulkan-renderer/debug_callback.cpp, src/vulkan-renderer/debug_marker_manager.cpp, src/vulkan-renderer/descriptor_manager.cpp, src/vulkan-renderer/error_handling.cpp, src/vulkan-renderer/fence_manager.cpp, src/vulkan-renderer/fps_counter.cpp, src/vulkan-renderer/gltf-model/bounding_box.cpp, src/vulkan-renderer/gltf-model/manager.cpp, src/vulkan-renderer/gpu_info.cpp, src/vulkan-renderer/mesh_buffer_manager.cpp, src/vulkan-renderer/renderer.cpp, src/vulkan-renderer/semaphore_manager.cpp, src/vulkan-renderer/settings_decision_maker.cpp, src/vulkan-renderer/shader_manager.cpp, src/vulkan-renderer/texture.cpp, src/vulkan-renderer/texture_manager.cpp, src/vulkan-renderer/thread_pool.cpp, src/vulkan-renderer/tools/cla_parser.cpp
Clang-Tidy make brackets in if cases a requirement. Also enabled the other google checks, like using namespace.
=> Tweak trivial things & adjust clang-tidy

.github/workflows/build_cmake.yml
- Remove clang-tidy analyze step in preparation for new code-style workflow
- Also removed `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`
- Prefixed all `env` variables with `inexor_`
=> [ci] Remove analyze step

documentation/source/development/building.rst
* Add ubuntu
* Fix text referencing a closed issue
=> Improve build-docs

.github/workflows/build.yml, README.rst
Renamed the cmake_build to just build.
=> [ci] Use Ubuntu 20.04

include/inexor/vulkan-renderer/renderer.hpp, include/inexor/vulkan-renderer/wrapper/vma.hpp, src/CMakeLists.txt, src/vulkan-renderer/application.cpp, src/vulkan-renderer/renderer.cpp, src/vulkan-renderer/wrapper/vma.cpp
=> VMA RAII wrapper refactoring.

include/inexor/vulkan-renderer/renderer.hpp, include/inexor/vulkan-renderer/settings_decision_maker.hpp, include/inexor/vulkan-renderer/wrapper/swapchain.hpp, src/CMakeLists.txt, src/vulkan-renderer/application.cpp, src/vulkan-renderer/renderer.cpp, src/vulkan-renderer/settings_decision_maker.cpp, src/vulkan-renderer/wrapper/swapchain.cpp
RAII refactoring continues.
As with previous pull requests, I didn't split up availability checks or settings decision manager yet.
=> Swapchain RAII wrapper refactoring.

shaders/fragmentshader.frag, shaders/vertexshader.vert
[https://github.com/Overv/VulkanTutorial/issues/112](https://github.com/Overv/VulkanTutorial/issues/112)
=> [shaders] Remove GL_ARB_separate_shader_objects

include/inexor/vulkan-renderer/renderer.hpp, include/inexor/vulkan-renderer/wrapper/glfw_context.hpp, include/inexor/vulkan-renderer/wrapper/window.hpp, include/inexor/vulkan-renderer/wrapper/window_surface.hpp, src/CMakeLists.txt, src/vulkan-renderer/application.cpp, src/vulkan-renderer/renderer.cpp, src/vulkan-renderer/wrapper/glfw_context.cpp, src/vulkan-renderer/wrapper/window.cpp, src/vulkan-renderer/wrapper/window_surface.cpp
RAII refactoring of glfw windows and `VkSurfaceKHR`.
=> Window and surface RAII wrapper refactoring.

include/inexor/vulkan-renderer/renderer.hpp, include/inexor/vulkan-renderer/wrapper/framebuffer.hpp, include/inexor/vulkan-renderer/wrapper/swapchain.hpp, src/CMakeLists.txt, src/vulkan-renderer/renderer.cpp, src/vulkan-renderer/wrapper/framebuffer.cpp
One of the last RAII refactorings.
=> VkFramebuffer RAII wrapper refactoring.

include/inexor/vulkan-renderer/renderer.hpp, include/inexor/vulkan-renderer/wrapper/descriptor.hpp, include/inexor/vulkan-renderer/wrapper/gpu_memory_buffer.hpp, include/inexor/vulkan-renderer/wrapper/mesh_buffer.hpp, include/inexor/vulkan-renderer/wrapper/once_command_buffer.hpp, include/inexor/vulkan-renderer/wrapper/shader.hpp, include/inexor/vulkan-renderer/wrapper/staging_buffer.hpp, include/inexor/vulkan-renderer/wrapper/texture.hpp, include/inexor/vulkan-renderer/wrapper/uniform_buffer.hpp, src/CMakeLists.txt, src/vulkan-renderer/wrapper/descriptor.cpp, src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp, src/vulkan-renderer/wrapper/mesh_buffer.cpp, src/vulkan-renderer/wrapper/once_command_buffer.cpp, src/vulkan-renderer/wrapper/shader.cpp, src/vulkan-renderer/wrapper/staging_buffer.cpp, src/vulkan-renderer/wrapper/texture.cpp, src/vulkan-renderer/wrapper/uniform_buffer.cpp
In this small pull request, I made sure all RAII classes are in the folder (and namespace) `wrapper`.
=> Made sure all RAII classes are in folder and namespace 'wrapper'.

README.rst
I updated the main start page.
* Removed Travis CI badge.
* Vulkan intro text has been improved.
* Deleted release plan, we will announce in discord if we need to.
* Fixed "Who supports Vulkan" part.
=> [update] Updated startpage.

.github/workflows/build.yml
=> [ci] Remove mingw gcc

src/vulkan-renderer/frame_graph.cpp, src/vulkan-renderer/wrapper/device.cpp, src/vulkan-renderer/wrapper/texture.cpp
Close https://github.com/inexorgame/vulkan-renderer/issues/211.
=> Fix MSVC build on Windows.

src/vulkan-renderer/availability_checks.cpp
Hello,
This is for issue #215 .
Let me know if you have comments or need changes.
Thanks.
=> [refactor] std::find for search loops

include/inexor/vulkan-renderer/imgui.hpp, src/vulkan-renderer/imgui.cpp, src/vulkan-renderer/wrapper/graphics_pipeline.cpp
Fix some clang-tidy warnings, and simplify vulkan code a bit.
=> ImGUI cleanup

include/inexor/vulkan-renderer/wrapper/once_command_buffer.hpp, src/vulkan-renderer/tools/file.cpp, src/vulkan-renderer/wrapper/fence.cpp, src/vulkan-renderer/wrapper/once_command_buffer.cpp, src/vulkan-renderer/wrapper/uniform_buffer.cpp, src/vulkan-renderer/wrapper/window.cpp
Closes https://github.com/inexorgame/vulkan-renderer/issues/260.
=> [assertions] Remove unnecessary assertions

src/vulkan-renderer/application.cpp
Closes https://github.com/inexorgame/vulkan-renderer/issues/300.
=> Fix --gpu command line argument

src/vulkan-renderer/imgui.cpp
Can you check why the first line changed?
=> [renderer] Fix image attachment initial layout for imgui renderpass

include/inexor/vulkan-renderer/application.hpp, include/inexor/vulkan-renderer/camera.hpp, include/inexor/vulkan-renderer/input/keyboard_mouse_data.hpp, include/inexor/vulkan-renderer/renderer.hpp, include/inexor/vulkan-renderer/wrapper/window.hpp, src/vulkan-renderer/application.cpp, src/vulkan-renderer/camera.cpp, src/vulkan-renderer/input/keyboard_mouse_data.cpp, src/vulkan-renderer/renderer.cpp, src/vulkan-renderer/wrapper/window.cpp
Closes https://github.com/inexorgame/vulkan-renderer/issues/299
Closes https://github.com/inexorgame/vulkan-renderer/issues/243
Closes https://github.com/inexorgame/vulkan-renderer/issues/264
Closes https://github.com/inexorgame/vulkan-renderer/issues/292
=> [camera] Implement WASD camera.

documentation/source/development/engine-design/labeling.rst, include/inexor/vulkan-renderer/render_graph.hpp, include/inexor/vulkan-renderer/renderer.hpp, src/CMakeLists.txt, src/vulkan-renderer/application.cpp, src/vulkan-renderer/render_graph.cpp, src/vulkan-renderer/renderer.cpp
We'll also need to rename the github label.
=> [render-graph] Rename FrameGraph to RenderGraph

README.rst, documentation/source/conf.py, documentation/source/development/building.rst, documentation/source/development/getting-started.rst, documentation/source/development/platforms.rst, documentation/source/index.rst, documentation/source/license/main.rst
Implementing the improvements mentioned in #338 and thus resolves #338.
=> [docs] Navigation improvements, update Ubuntu setup, add troubleshooting

src/vulkan-renderer/imgui.cpp, src/vulkan-renderer/wrapper/cpu_texture.cpp, src/vulkan-renderer/wrapper/descriptor.cpp, src/vulkan-renderer/wrapper/device.cpp, src/vulkan-renderer/wrapper/fence.cpp, src/vulkan-renderer/wrapper/framebuffer.cpp, src/vulkan-renderer/wrapper/glfw_context.cpp, src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp, src/vulkan-renderer/wrapper/gpu_texture.cpp, src/vulkan-renderer/wrapper/graphics_pipeline.cpp, src/vulkan-renderer/wrapper/image.cpp, src/vulkan-renderer/wrapper/instance.cpp, src/vulkan-renderer/wrapper/renderpass.cpp, src/vulkan-renderer/wrapper/semaphore.cpp, src/vulkan-renderer/wrapper/shader.cpp, src/vulkan-renderer/wrapper/swapchain.cpp, src/vulkan-renderer/wrapper/window.cpp, src/vulkan-renderer/wrapper/window_surface.cpp
Closes https://github.com/inexorgame/vulkan-renderer/issues/347
=> [destructors] Remove unnecessary spdlog messages

include/inexor/vulkan-renderer/world/cube.hpp, src/vulkan-renderer/application.cpp, src/vulkan-renderer/world/cube.cpp
Close #345
Close #346 
Close #349
=> [octree] Fix parent bugs

include/inexor/vulkan-renderer/vk_tools/gpu_info.hpp, include/inexor/vulkan-renderer/vk_tools/representation.hpp, src/vulkan-renderer/vk_tools/gpu_info.cpp, src/vulkan-renderer/vk_tools/representation.cpp
=> [gpu-info] Cleanup

documentation/source/contributing/contribute-code.rst, documentation/source/development/reference/keyboard-mouse-input.rst, documentation/source/development/reference/main.rst, documentation/source/faq/main.rst
Closes https://github.com/inexorgame/vulkan-renderer/issues/336
Closes https://github.com/inexorgame/vulkan-renderer/issues/334
Closes https://github.com/inexorgame/vulkan-renderer/issues/331
=> [docs] Wiki update 3

README.rst, documentation/source/images/icon_CLion.svg
=> [doc] Add CLion sponsoring label to main page

README.rst
=> [doc] Reduce number of badges

benchmarks/world/cube_collision.cpp, include/inexor/vulkan-renderer/bezier_curve.hpp, include/inexor/vulkan-renderer/camera.hpp, include/inexor/vulkan-renderer/render_graph.hpp, include/inexor/vulkan-renderer/renderer.hpp, include/inexor/vulkan-renderer/settings_decision_maker.hpp, include/inexor/vulkan-renderer/time_step.hpp, include/inexor/vulkan-renderer/world/collision.hpp, include/inexor/vulkan-renderer/wrapper/device.hpp, include/inexor/vulkan-renderer/wrapper/fence.hpp, include/inexor/vulkan-renderer/wrapper/instance.hpp, include/inexor/vulkan-renderer/wrapper/swapchain.hpp, src/vulkan-renderer/application.cpp, src/vulkan-renderer/imgui.cpp, src/vulkan-renderer/settings_decision_maker.cpp, src/vulkan-renderer/vk_tools/gpu_info.cpp, src/vulkan-renderer/vk_tools/representation.cpp, src/vulkan-renderer/wrapper/device.cpp, src/vulkan-renderer/wrapper/gpu_texture.cpp
Also check out https://github.com/inexorgame/vulkan-renderer/issues/413
=> [*] Fix typos and remove semicolons for namespaces

include/inexor/vulkan-renderer/input/keyboard_mouse_data.hpp, src/vulkan-renderer/application.cpp, src/vulkan-renderer/input/keyboard_mouse_data.cpp
Closes #410 
Thank you @westernheld for finding this issue!
=> [input] Ignore invalid key ids and button ids

documentation/requirements.txt
Fix sphinx documentation again.
Thanks to @IceflowRE for coming up with a solution for this.
=> [doc] Fix documentation build

documentation/source/development/building.rst
Thanks to Discord user `blopr` for the feedback!
=> [doc] Add build instructions for Debian

cmake/conan_setup.cmake
=> [conan] Migrate to new conan center

example/main.cpp, include/inexor/vulkan-renderer/meta.hpp.in, include/inexor/vulkan-renderer/settings_decision_maker.hpp, include/inexor/vulkan-renderer/vk_tools/gpu_info.hpp, include/inexor/vulkan-renderer/wrapper/device.hpp, include/inexor/vulkan-renderer/wrapper/instance.hpp, src/vulkan-renderer/application.cpp, src/vulkan-renderer/renderer.cpp, src/vulkan-renderer/settings_decision_maker.cpp, src/vulkan-renderer/vk_tools/gpu_info.cpp, src/vulkan-renderer/wrapper/command_pool.cpp, src/vulkan-renderer/wrapper/cpu_texture.cpp, src/vulkan-renderer/wrapper/descriptor.cpp, src/vulkan-renderer/wrapper/device.cpp, src/vulkan-renderer/wrapper/fence.cpp, src/vulkan-renderer/wrapper/framebuffer.cpp, src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp, src/vulkan-renderer/wrapper/gpu_texture.cpp, src/vulkan-renderer/wrapper/instance.cpp, src/vulkan-renderer/wrapper/once_command_buffer.cpp, src/vulkan-renderer/wrapper/semaphore.cpp, src/vulkan-renderer/wrapper/staging_buffer.cpp, src/vulkan-renderer/wrapper/swapchain.cpp, src/vulkan-renderer/wrapper/window_surface.cpp
Closes https://github.com/inexorgame/vulkan-renderer/issues/224
Closes https://github.com/inexorgame/vulkan-renderer/issues/403
Closes https://github.com/inexorgame/vulkan-renderer/issues/358
Closes https://github.com/inexorgame/vulkan-renderer/issues/344
Closes https://github.com/inexorgame/vulkan-renderer/issues/309
Closes https://github.com/inexorgame/vulkan-renderer/issues/218
Closes https://github.com/inexorgame/vulkan-renderer/issues/307
Closes https://github.com/inexorgame/vulkan-renderer/issues/330
=> [*] Miscellaneous fixes and switch to VK_API_VERSION_1_2

.clang-tidy, .github/workflows/build.yml, .github/workflows/static_analysis.yml, src/vulkan-renderer/io/byte_stream.cpp, src/vulkan-renderer/world/cube.cpp
=> [ci] Update Vulkan SDK version and fix clang-tidy warnings

src/vulkan-renderer/wrapper/descriptor.cpp, src/vulkan-renderer/wrapper/fence.cpp, src/vulkan-renderer/wrapper/framebuffer.cpp, src/vulkan-renderer/wrapper/gpu_texture.cpp, src/vulkan-renderer/wrapper/once_command_buffer.cpp, src/vulkan-renderer/wrapper/semaphore.cpp, src/vulkan-renderer/wrapper/shader.cpp, src/vulkan-renderer/wrapper/swapchain.cpp
=> [*] Further reduce use of spdlog messages

.github/workflows/build.yml, cmake/conan_setup.cmake
=> [ci] Use Visual Studio 2022

shaders/CMakeLists.txt
=> [cmake] Show shader files in VS project filter

README.rst
It's the small things in life you know..
=> [readme] Change readme badge to C++20

.github/workflows/build.yml, .github/workflows/build_documentation.yml, .github/workflows/code_style.yml, .github/workflows/commit_naming.yml, .github/workflows/static_analysis.yml, documentation/requirements.txt, include/inexor/vulkan-renderer/world/cube.hpp, include/inexor/vulkan-renderer/wrapper/mesh_buffer.hpp, src/vulkan-renderer/io/nxoc_parser.cpp, src/vulkan-renderer/world/cube.cpp
=> [ci] Fix ci

documentation/source/development/building.rst
Tested in Fedora 35, 36, 37 with [this setup](https://gist.github.com/sleroq/9e66b117c3ea6d126f71e66ac1f559f1)
=> Added build instructions for Fedora

.github/workflows/build.yml, .github/workflows/build_documentation.yml, .github/workflows/release.yml, .github/workflows/static_analysis.yml, CMakeLists.txt, conanfile.py, helper/req_check.py, include/inexor/vulkan-renderer/world/cube.hpp, src/CMakeLists.txt
=> Add Windows Clang build

include/inexor/vulkan-renderer/vk_tools/representation.hpp, src/vulkan-renderer/vk_tools/representation.cpp
=> [representation] Fix msvc warning

.github/workflows/release.yml
=> [workflows] Fix automatic generation of releases

.github/workflows/release.yml
Closes https://github.com/inexorgame/vulkan-renderer/issues/531
Sorry, my bad!
Thanks again @IceflowRE
=> [workflows] Fix automatic release generation when a pull request is merged into main

.github/workflows/release.yml
Attempt no. 2 to fix automatic release generation.
=> [workflows] Fix automatic release generation

.readthedocs.yml
Closes https://github.com/inexorgame/vulkan-renderer/issues/564
Solution: We need to specify the os!
=> [doc] Fix setup of readthedocs

.github/workflows/release.yml
This will hopefully fix release script.
=> [ci] Fix release workflow

.github/workflows/release.yml
This should fix the release workflow.
=> [ci] Simplify and fix release workflow

.github/workflows/add_labels.yaml, .github/workflows/build.yml, .github/workflows/build_documentation.yml, .github/workflows/code_style.yml, .github/workflows/commit_naming.yml, .github/workflows/release.yml, .github/workflows/remove_labels.yaml, .github/workflows/static_analysis.yml
=> [ci] Attempt to fix release workflow

.github/workflows/release.yml
=> [ci] Fix nightly release so it includes documentation

.github/workflows/build.yml
This will display the console output of running the benchmarks and also log
=> [ci] Print output of running benchmarks to console and to logfile
