- src/vulkan-renderer/command-buffer-recording/single_time_command_buffer.cpp
- src/vulkan-renderer/error-handling/error_handling.cpp
- src/vulkan-renderer/texture-manager/texture_manager.cpp
The typewriter apostrophe is used everywhere else.
> Replace apostrophe with typewriter apostrophe

- CMakeLists.txt
- src/vulkan-renderer/renderer.cpp
Adds a new configure option to cmake. This fixes #19 as linux users can now pass -DUSE_VMA_RECORDING=Off to disable vulkan memory allocator's recording feature.
> Add USE_VMA_RECORDING cmake option

- src/vulkan-renderer/renderer.cpp
_DEBUG is a non-standard MSVC defined macro.
- Replace all uses of `#if defined(_DEBUG)` with `#ifndef NDEBUG`
- Replace all uses of `#if !defined(_DEBUG)` with `#ifdef NDEBUG`
> Replace _DEBUG with NDEBUG

- .git-blame-ignore-revs
Add .git-blame-ignores-revs that contains the recent clang-format commits.
> [vcs] Add .git-blame-ignore-revs file

- src/vulkan-renderer/renderer.hpp
Remove an unneeded `using namespace std` in renderer.hpp
> Remove spurious using namespace std

- include/inexor/vulkan-renderer/camera.hpp
- include/inexor/vulkan-renderer/debug_marker_manager.hpp
- include/inexor/vulkan-renderer/descriptor_manager.hpp
- include/inexor/vulkan-renderer/fence_manager.hpp
- include/inexor/vulkan-renderer/single_time_command_buffer.hpp
Removes all const qualifiers for value parameters in headers. These const qualifiers should only be put in the declaration (source file) and not in the definition (header file).
> Remove unnecessary const qualifiers

- configuration/renderer.toml
- include/inexor/vulkan-renderer/application.hpp
- src/vulkan-renderer/application.cpp
This pull request cleans up `Application::load_toml_configuration` by:
- Simplifying the file handling code
- Fixing the typo when setting `window_height`
- Removing unnecessary new lines
> [code] Cleanup Application::load_toml_configuration

- .github/workflows/build_cmake.yml
- Reformatted whole file
- Cleaned up arguments
- Made all `cmake` arguments go over multiple lines
- Made all `apt install` arguments go over multiple lines
- Added a few comments
- Renamed `Create CMake` to `Configure CMake`
- Renamed all uses of `CLang` to `Clang`
- Remove all dependency installs - only build tools are installed now
- Fixed clang build
- Switched to using `lld` on clang build
- Removed passing `-DINEXOR_CONAN_PROFILE` in cmake configure stage
- Use `env` for variables the same across jobs. These variables are now in `env`:
- `build_type`
- `conan_path`
- `vulkan_sdk`
- `vulkan_version`
> [ci] Cleanup and fix clang build

- CMakeLists.txt
- benchmarks/CMakeLists.txt
- example/CMakeLists.txt
- src/CMakeLists.txt
- tests/CMakeLists.txt
- Cleanup option checks in root `CMakeLists.txt`
- Merge simple statements onto one line
- Make `target_compile_definitions` for `inexor-vulkan-renderer` target `PUBLIC`
- This changes makes it so a program linking against `inexor-vulkan-renderer` also has `GLM_FORCE_RADIANS` set
> [cmake] Cleanup

- include/inexor/vulkan-renderer/shader.hpp
- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/renderer.cpp
- src/vulkan-renderer/shader.cpp
- Fixed crash
- Implemented move constructor for shader
- Also had to make sure shader vector was clear at the top of `shutdown_vulkan`
- Cleaned up constructors
- Switched to using initialiser lists
- Switched to using a cascading constructor to avoid code duplication
- Cleaned up file handling code
- Refactored includes
- Moved some includes to source file
- Added some missing includes
- Made vulkan handles be passed by value instead of const reference
- Made strings be passed by const reference instead of value to avoid copy
- Remove vma allocator from shader
- Removed a c style cast
- Removed trailing commas from namespace declarations
- Lots of renaming
- Renamed `nameInfo` to `name_info`
- Renamed `shader_memory` to `code`
- Renamed `shader_create_info` to just `create_info`
> [code] Cleanup shader

- .git-blame-ignore-revs
- include/inexor/vulkan-renderer/world/cube.hpp
- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/world/bit_stream.cpp
- src/vulkan-renderer/world/cube.cpp
This PR aims at adding overloading `=` for the `Cube`-class and overloading the `=`, `-=`, and `+=` for the `Indentation` class.
As I'm fairly new to C++, I would love to see a review considering the following question on the aspect of overloading ([this commit](https://github.com/inexorgame/vulkan-renderer/commit/348725dbf61b431ef68bf625d28ef3365bc5646f#diff-6512ac26a57b9dab0cfd3b6edfeacc41) and [this commit](https://github.com/inexorgame/vulkan-renderer/commit/1c27f8c9cab842cbc597d76e4964c13f1fce7b3f#diff-6512ac26a57b9dab0cfd3b6edfeacc41)):
Does it work as one would expect (i.e., does it follow the C++ best practices)? Are the copy-constructors and the lhs & rhs overloads correctly implemented?
> Octree: Bug-fixes and overloading

- .clang-tidy
Was giving this warning `Do not implicitly decay an array into a pointer; consider using gsl::array_view or an explicit cast instead` on every `assert`.
> [clang-tidy] Disable cppcoreguidelines-pro-bounds-array-to-pointer-decay

- example/main.cpp
- include/inexor/vulkan-renderer/application.hpp
- include/inexor/vulkan-renderer/tools/cla_parser.hpp
- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/tools/cla_parser.cpp
- Refactored `CommandLineArgumentValue` by making a templated `as` function
- Also removed `CommnandLineArgumentType`
- Refactored `CommandLineArgumentParser`
- Shortened names
-  Rewrote `parse_args` function
- Made the parser a member of `Application` rather than inheriting from it
- Made command line arguments follow more of a posix/gnu style
> Cleanup command line parser

- example/main.cpp
Including the process id in the log is a bit unnecessary and doesn't really help with debugging.
> [example] Remove process id from log

- include/inexor/vulkan-renderer/once_command_buffer.hpp
- include/inexor/vulkan-renderer/renderer.hpp
- include/inexor/vulkan-renderer/wrapper/command_pool.hpp
- src/CMakeLists.txt
- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/once_command_buffer.cpp
- src/vulkan-renderer/renderer.cpp
- src/vulkan-renderer/wrapper/command_pool.cpp
In this pull request, I added a RAII wrapper for `VkCommandPool` and replaced the command pool of the renderer and the once command buffer class with the wrapper.
> VkCommandPool RAII wrapper refactoring.

- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/gpu_info.cpp
- src/vulkan-renderer/renderer.cpp
- src/vulkan-renderer/world/cube.cpp
- src/vulkan-renderer/wrapper/instance.cpp
- src/vulkan-renderer/wrapper/swapchain.cpp
Prefer `auto *` to `auto` for types where the right hand side is a pointer. This makes it clear that the deduced type is a pointer and that the right hand side isn't being copied.
> [*] Prefer auto *

- include/inexor/vulkan-renderer/octree_vertex.hpp
- include/inexor/vulkan-renderer/renderer.hpp
- include/inexor/vulkan-renderer/wrapper/graphics_pipeline.hpp
- include/inexor/vulkan-renderer/wrapper/pipeline_layout.hpp
- include/inexor/vulkan-renderer/wrapper/renderpass.hpp
- src/CMakeLists.txt
- src/vulkan-renderer/octree_vertex.cpp
- src/vulkan-renderer/renderer.cpp
- src/vulkan-renderer/wrapper/graphics_pipeline.cpp
- src/vulkan-renderer/wrapper/pipeline_layout.cpp
- src/vulkan-renderer/wrapper/renderpass.cpp
In this RAII refactoring, I encapsulate:
* `VkPipelineLayout`
* `VkRenderPass`
* `VkPipeline` and `VkPipelineCache` (one wrapper)
This is the refactoring where we have the most parameters in our constructors.
I think most of it needs to be extended in the future again (especially renderpasses), as mentioned in the TODOs.
But for now, this really simplifies the code and further decreases the size of `renderer.cpp`.
> Vulkan pipeline RAII wrapper refactoring.

- src/vulkan-renderer/renderer.cpp
- src/vulkan-renderer/wrapper/fence.cpp
- src/vulkan-renderer/wrapper/framebuffer.cpp
- src/vulkan-renderer/wrapper/graphics_pipeline.cpp
- src/vulkan-renderer/wrapper/image.cpp
- src/vulkan-renderer/wrapper/pipeline_layout.cpp
- src/vulkan-renderer/wrapper/renderpass.cpp
- src/vulkan-renderer/wrapper/semaphore.cpp
This small pull request moves spdlog trace messages to the corresponding destructor.
> Moved spdlog trace messages to RAII destructors.

- CMakeLists.txt
This allows us to use link time optimization through cmake, as the `INTERPROCEDURAL_OPTIMIZATION` target property was ignored in versions before 3.9.
> [cmake] Bump minimum version to 3.9

- src/CMakeLists.txt
This will close https://github.com/inexorgame/vulkan-renderer/issues/128.
You can see the folder structure is now represented in Visual Studio category filters:
> [meta] Display folder structure in Visual Studio.

- .github/workflows/code_style.yml
- Run clang-format on diff of PR
- Only works on PRs were the base branch is master, I couldn't figure out a way to get the current branch in actions
- Doesn't change any code, only fails if the code hasn't been formatted properly.
> [ci] Add clang format check

- include/inexor/vulkan-renderer/wrapper/device.hpp
- src/vulkan-renderer/frame_graph.cpp
- src/vulkan-renderer/wrapper/command_buffer.cpp
- src/vulkan-renderer/wrapper/device.cpp
- src/vulkan-renderer/wrapper/fence.cpp
- src/vulkan-renderer/wrapper/framebuffer.cpp
- src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp
- src/vulkan-renderer/wrapper/gpu_texture.cpp
- src/vulkan-renderer/wrapper/image.cpp
- src/vulkan-renderer/wrapper/resource_descriptor.cpp
- src/vulkan-renderer/wrapper/semaphore.cpp
- src/vulkan-renderer/wrapper/shader.cpp
- src/vulkan-renderer/wrapper/swapchain.cpp
In this pull request, I removed the old `set_object_name` method and overloaded the wrapper which assigns an internal name to Vulkan resources using `PFN_vkDebugMarkerSetObjectNameEXT`. This simplifies the interface and reduces the need to use a `reinterpret_cast` as argument every function call. This means we don't need to pass a pointer to the method, furter improving type safety.
**Old code example:**
* Uses `reinterpret_cast` in every method call, bad!
* User needs to specify `VK_DEBUG_REPORT...` type in every method call, bad!
```cpp
m_device.set_object_name(reinterpret_cast<std::uint64_t>(m_fence), VK_DEBUG_REPORT_OBJECT_TYPE_FENCE_EXT, m_name);
```
**New code example:**
* Less arguments, good.
* Improved type safety.
```cpp
m_device.set_debug_marker_name(m_fence, m_name);
``` …
> Refactor Vulkan debug markers

- include/inexor/vulkan-renderer/application.hpp
- include/inexor/vulkan-renderer/input/keyboard_mouse_data.hpp
- include/inexor/vulkan-renderer/wrapper/window.hpp
- src/CMakeLists.txt
- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/input/keyboard_mouse_data.cpp
- src/vulkan-renderer/wrapper/window.cpp
Closes https://github.com/inexorgame/vulkan-renderer/issues/273.
This PR fixes the following issues:
You can't use a class method in glfw3 because it is a C-style API. This means you can't directly pass a class method into one of the previously mentioned glfw functions. You can find more in [this stackoverflow post](https://stackoverflow.com/questions/7676971/pointing-to-a-function-that-is-a-class-member-glfw-setkeycallback). However, we go around this issue by storing the pointer to the application's instance in the glfw window user pointer. Then we set up the callbacks in lambdas, which get this pointer and redirect the event to the class method for callback handling. This is a strange way of doing it, but it's the way how it's done in the official Vulkan demos as well. Again: This is a …
> Use glfw callbacks instead of polling events manually

- include/inexor/vulkan-renderer/world/cube.hpp
- include/inexor/vulkan-renderer/world/indentation.hpp
- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/world/cube.cpp
- src/vulkan-renderer/world/indentation.cpp
Related to: #230.
Changes:
- the `child`/ `childs` -> `children` refactor will be done in another PR after this one.
- I used a template function to distiguish between the 90/180/270 degree rotations.
There were some other ideas which can be done:
- The public function of the rotate function can be done differently:
(current version, but uses the function below behind the scenes)
```c++
void rotate(const RotationAxis::Type &axis, int rotations);
```
(this is used behind the function shown above, but can replaced as the public version)
```c++
template <int Rotations>
void rotate(const RotationAxis::Type &axis);
```
This is another version which is possible, the `RotationAxis` will be an enum here.
But this will use the template function above behind the scenes.
```c++
template …
```
> [octree] Add rotation function

- .github/workflows/commit_naming.yml
- helper/gitcc/gitcc/main.py
- helper/gitcc/gitcc/utility.py
- helper/gitcc/setup.py
It is pretty obvious that commit summaries should follow a specific pattern. It makes it a lot easier to find commits which you search for.
Our current format is something like `[sound] Updated the fox sound`.
The added workflow will check the commit on push and all commits of an PR.
This tool will **not** prevent the merge commit name to be `Merge pull request #xxx from yyyy`, we have to remember ourself to change the merge summary ourself to `[merge] Bla bla`
`[<category>] <Description>`
The category text can only include lower case letters, numbers, `|`, `-` and spaces and must be at least two characters. If the commit applies to various topics e.g. sound and rendering you write `[sound|rendering]`.
The description should start with an capital letter or number and must contain at least …
> [ci] Add commit naming check

- include/inexor/vulkan-renderer/wrapper/gpu_memory_buffer.hpp
This was giving VMA uninitialised data, which was sometimes causing
segfaults.
> [wrapper] Make sure to zero-out VMA structs

- src/vulkan-renderer/vk_tools/gpu_info.cpp
This caused the engine to crash if a system has no device layers available. There should be no exceptions thrown in this case, since that code part is printing gpu info only.
> [gpu-info] Don't use exceptions in gpu info

- src/vulkan-renderer/vk_tools/gpu_info.cpp
If gpu info queries are empty it's not an error, it's a valid use case.
> [gpu-info] Don't display empty gpu info queries as error

- src/vulkan-renderer/wrapper/command_pool.cpp
- src/vulkan-renderer/wrapper/cpu_texture.cpp
- src/vulkan-renderer/wrapper/descriptor.cpp
- src/vulkan-renderer/wrapper/device.cpp
- src/vulkan-renderer/wrapper/fence.cpp
- src/vulkan-renderer/wrapper/framebuffer.cpp
- src/vulkan-renderer/wrapper/glfw_context.cpp
- src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp
- src/vulkan-renderer/wrapper/gpu_texture.cpp
- src/vulkan-renderer/wrapper/image.cpp
- src/vulkan-renderer/wrapper/instance.cpp
- src/vulkan-renderer/wrapper/semaphore.cpp
- src/vulkan-renderer/wrapper/shader.cpp
- src/vulkan-renderer/wrapper/swapchain.cpp
- src/vulkan-renderer/wrapper/window.cpp
- src/vulkan-renderer/wrapper/window_surface.cpp
It's not illegal to call all those Vulkan functions on invalid objects. We don't need those checks.
Tested on Ubuntu and Windows.
> [destructors] Remove unnecessary if checks

- include/inexor/vulkan-renderer/io/nxoc_parser.hpp
- include/inexor/vulkan-renderer/io/octree_parser.hpp
This was breaking build with latest GCC.
> [io] Add missing cstdint include

- CMakeLists.txt
- benchmarks/CMakeLists.txt
- benchmarks/engine_benchmark_main.cpp
- src/CMakeLists.txt
- tests/CMakeLists.txt
- tests/unit_tests_main.cpp
Closes https://github.com/inexorgame/vulkan-renderer/issues/360
I would like this to be merged into `hanni/version_constexpr_fix`.
Tested on Ubuntu 20.04 and Windows.
> [tests|benchmarks] Print engine metadata in unit tests and benchmarks

- CMakeLists.txt
- cmake/conan_setup.cmake
- src/CMakeLists.txt
Can you confirm it fixes the issue and it is really build against the debug and release libraries.
Based on #368 
Close #228
Close #372
> [cmake] Fix cmake gui multi config generation

- src/vulkan-renderer/wrapper/device.cpp
- src/vulkan-renderer/wrapper/instance.cpp
Closes https://github.com/inexorgame/vulkan-renderer/issues/389
Also: copy paste errors in action haha
```cpp
if (device_layer_count == 0) {
throw std::runtime_error("Error: No Vulkan device extensions available!");
}
```
> [device|instance] Don't throw exception when it's not an error

- configuration/renderer.toml
- include/inexor/vulkan-renderer/renderer.hpp
- include/inexor/vulkan-renderer/wrapper/window.hpp
- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/wrapper/window.cpp
References issue #291 
This commit adds a new TOML variable which changes the window mode to use on start-up.
The TOML configuration file uses strings to indicate which mode should be used
- windowed
- windowed-fullscreen
- fullscreen
~~Ability to change window mode during runtime~~ (moved to https://github.com/inexorgame/vulkan-renderer/issues/328)
Feedback welcome of course
> Added configurable window modes

- documentation/source/development/reference/keyboard-mouse-input.rst
- include/inexor/vulkan-renderer/input/keyboard_mouse_data.hpp
- src/vulkan-renderer/input/keyboard_mouse_data.cpp
Closes https://github.com/inexorgame/vulkan-renderer/issues/400
This makes the input class thread safe and uses a `std::vector` instead of an `std::unordered_map` to store the keys.
> [input] Refactoring

- include/inexor/vulkan-renderer/exception.hpp
- include/inexor/vulkan-renderer/vk_tools/representation.hpp
- src/vulkan-renderer/exception.cpp
- src/vulkan-renderer/vk_tools/gpu_info.cpp
- src/vulkan-renderer/vk_tools/representation.cpp
> [representation|gpu-info] Refactoring

- include/inexor/vulkan-renderer/world/cube.hpp
- src/vulkan-renderer/world/cube.cpp
- tests/CMakeLists.txt
- tests/world/cube.cpp
Implementing the neighbors method requested in #190 (with a slightly different method signature).
I think we should wait for #368, #262, and #342 before merging this.
Still, it would be great already get feedback on the code. :)
I didn't check it on clang-tidy right now because I expect a lot of changes in this regard with #342.
> [octree] Get neighboring cubes

- conanfile.py
We don't need `vulkan-headers/1.2.172` as it will be required by `vulkan-memory-allocator/2.3.0`.
> [conan] Fix minor warnings

- example/CMakeLists.txt
Let's ignore this entirely since it's not important at all
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4099?view=msvc-170
https://stackoverflow.com/questions/25843883/how-to-remove-warning-lnk4099-pdb-lib-pdb-was-not-found
> [cmake] Ignore msvc linker warning LNK4099

- include/inexor/vulkan-renderer/wrapper/instance.hpp
- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/wrapper/device.cpp
- src/vulkan-renderer/wrapper/instance.cpp
- ~~If the version of Vulkan API specified inside of the instance wrapper is greater than `VK_API_VERSION_1_1`, tell Vulkan memory allovator (VMA) to use no newer version than `VK_API_VERSION_1_1` anyways.~~
> [device|instance] Add missing Vulkan API version checks

- include/inexor/vulkan-renderer/render_graph.hpp
- include/inexor/vulkan-renderer/wrapper/command_pool.hpp
- include/inexor/vulkan-renderer/wrapper/cpu_texture.hpp
- include/inexor/vulkan-renderer/wrapper/device.hpp
- include/inexor/vulkan-renderer/wrapper/gpu_texture.hpp
- include/inexor/vulkan-renderer/wrapper/once_command_buffer.hpp
- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/render_graph.cpp
- src/vulkan-renderer/wrapper/command_pool.cpp
- src/vulkan-renderer/wrapper/descriptor.cpp
- src/vulkan-renderer/wrapper/device.cpp
- src/vulkan-renderer/wrapper/fence.cpp
- src/vulkan-renderer/wrapper/framebuffer.cpp
- src/vulkan-renderer/wrapper/gpu_texture.cpp
- src/vulkan-renderer/wrapper/image.cpp
- src/vulkan-renderer/wrapper/once_command_buffer.cpp
- src/vulkan-renderer/wrapper/semaphore.cpp
- src/vulkan-renderer/wrapper/shader.cpp
- src/vulkan-renderer/wrapper/staging_buffer.cpp
- src/vulkan-renderer/wrapper/swapchain.cpp
> Refactoring: Introduce wrapper functions for Vulkan create methods

- configuration/renderer.toml
- include/inexor/vulkan-renderer/camera.hpp
- src/vulkan-renderer/camera.cpp
Closes https://github.com/inexorgame/vulkan-renderer/issues/407
`glm::perspective` takes in the vertical FOV, so passing in a value of `90` gives us a horizontal FOV of `121`, which is pretty high. This PR adds a conversion before constructing the projection matrix, and also changes the default window size to have an aspect ratio of 16:9 (otherwise the hfov will equal vfov which makes things not look right)
> [camera] Make sure to convert horizontal fov to vertical fov before passing to glm

- src/vulkan-renderer/world/collision.cpp
I fixed this:
```cpp
command-pool-refactoring/vulkan-renderer/src/vulkan-renderer/world/collision.cpp:28:37:
warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
28 |     const auto adjust_coordinates = [=](const glm::vec3 pos) {
|                                     ^
command-pool-refactoring/vulkan-renderer/src/vulkan-renderer/world/collision.cpp:28:37:
note: add explicit ‘this’ or ‘*this’ capture
```
I can really recommend this ebook btw: https://leanpub.com/cpplambda
> [collision] Fix implicit lambda capture of 'this' using [=] which is deprecated in C++20

- example/main.cpp
- include/inexor/vulkan-renderer/wrapper/mesh_buffer.hpp
- src/vulkan-renderer/application.cpp
- src/vulkan-renderer/imgui.cpp
- src/vulkan-renderer/io/nxoc_parser.cpp
- src/vulkan-renderer/render_graph.cpp
- src/vulkan-renderer/renderer.cpp
- src/vulkan-renderer/settings_decision_maker.cpp
- src/vulkan-renderer/vk_tools/gpu_info.cpp
- src/vulkan-renderer/wrapper/cpu_texture.cpp
- src/vulkan-renderer/wrapper/device.cpp
- src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp
- src/vulkan-renderer/wrapper/instance.cpp
- src/vulkan-renderer/wrapper/swapchain.cpp
- src/vulkan-renderer/wrapper/window.cpp
- src/vulkan-renderer/wrapper/window_surface.cpp
- Remove unnecessary log messages
- Use log level trace consistently
- Do not end messages with `.`
- Do not print names of objects using ' '
- Use list style consistently when printing multiple items:
```
2022-05-14 21:12:30.551076 trace 43790 [vulkan-renderer] Window: Inexor-Vulkan-Renderer, 1280 x 720
2022-05-14 21:12:30.551122 trace 43790 [vulkan-renderer]    - assets/textures/texture_A_1024.jpg
2022-05-14 21:12:30.551127 trace 43790 [vulkan-renderer]    - assets/textures/texture_C_1024.jpg
2022-05-14 21:12:30.551124 trace 43790 [vulkan-renderer]    - assets/textures/texture_B_1024.jpg
2022-05-14 21:12:30.551129 trace 43790 [vulkan-renderer]    - assets/textures/texture_D_1024.jpg
2022-05-14 21:12:30.551131 trace 43790 [vulkan-renderer]    - assets/textures/texture_E_1024.jpg …
```
> [*] Cleanup of spdlog messages

- documentation/source/development/building.rst
- documentation/source/development/platforms.rst
Added the instructions for installing dependencies and tools on an Arch Linux system.
Kept installing every package I needed until the example binary compiled, wrote down all required packages here.
Tested on an Arch Linux machine, of course :)
> [docs] Added build dependencies and tools for Arch Linux systems

- CMakeLists.txt
This little CMake workaround forces ANSI-colored output from GCC/clang C++ compilers, even if you're using the Ninja build tool. By default there is no colored output using Ninja, because Ninja intercepts the terminal output from the compiler. Both compilers detect this and disable ANSI colors from their output. This workaround fixes that issue and helps make errors/warnings more readable.
> [cmake] Enable GCC/clang ANSI-colored terminal output for Ninja build tool

- include/inexor/vulkan-renderer/wrapper/descriptor_builder.hpp
- include/inexor/vulkan-renderer/wrapper/gpu_memory_buffer.hpp
- include/inexor/vulkan-renderer/wrapper/make_info.hpp
- src/vulkan-renderer/imgui.cpp
- src/vulkan-renderer/render_graph.cpp
- src/vulkan-renderer/renderer.cpp
- src/vulkan-renderer/wrapper/command_buffer.cpp
- src/vulkan-renderer/wrapper/command_pool.cpp
- src/vulkan-renderer/wrapper/descriptor.cpp
- src/vulkan-renderer/wrapper/descriptor_builder.cpp
- src/vulkan-renderer/wrapper/device.cpp
- src/vulkan-renderer/wrapper/fence.cpp
- src/vulkan-renderer/wrapper/framebuffer.cpp
- src/vulkan-renderer/wrapper/gpu_memory_buffer.cpp
- src/vulkan-renderer/wrapper/gpu_texture.cpp
- src/vulkan-renderer/wrapper/image.cpp
- src/vulkan-renderer/wrapper/instance.cpp
- src/vulkan-renderer/wrapper/make_info.cpp
- src/vulkan-renderer/wrapper/semaphore.cpp
- src/vulkan-renderer/wrapper/shader.cpp
- src/vulkan-renderer/wrapper/swapchain.cpp
[Designated initializers](https://en.cppreference.com/w/cpp/language/aggregate_initialization#Designated_initializers) are a C++20 feature that makes initialization code more readable. In addition it enforces that the order of initialization is the same as the order of declaration in the struct. Compare those two code parts:
**Old code:**
```cpp
VkImageMemoryBarrier barrier{};
barrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
barrier.oldLayout = old_layout;
barrier.newLayout = new_layout;
barrier.image = image;
barrier.subresourceRange = subres_range;
```
**New code with designated initializers**:
```cpp
const auto barrier = make_info<VkImageMemoryBarrier>({
.oldLayout = …
```
> Use C++20's designated initializers

- .github/workflows/build.yml
- .github/workflows/build_documentation.yml
- .github/workflows/release.yml
- .github/workflows/static_analysis.yml
- CMakeLists.txt
- conanfile.py
- helper/req_check.py
- include/inexor/vulkan-renderer/world/cube.hpp
- src/CMakeLists.txt
Will release ready to use archives under the release tab.
You can see it [here](https://github.com/IceflowRE/vulkan-renderer/releases).
I used the `Pre-Release` tag so it won't show up as the latest versoin. Which should be a stable one.
Also it is based on #491 
---
Close: #355
> Add latest development release

- tests/gpu-selection/selection.cpp
I was not respecting the order of declaration when using [designated initializers](https://en.cppreference.com/w/cpp/language/aggregate_initialization#Designated_initializers) in unit tests for physical device selection.
> [tests] Fix physical device selection tests

- include/inexor/vulkan-renderer/wrapper/device.hpp
- include/inexor/vulkan-renderer/wrapper/swapchain.hpp
- src/vulkan-renderer/renderer.cpp
- src/vulkan-renderer/wrapper/device.cpp
- src/vulkan-renderer/wrapper/swapchain.cpp
> [swapchain] Fix destruction bug

- .github/workflows/build.yml
- .github/workflows/static_analysis.yml
- CMakeLists.txt
- cmake/dependencies.cmake
- helper/req_check.py
- include/inexor/vulkan-renderer/world/cube.hpp
- include/inexor/vulkan-renderer/wrapper/swapchain.hpp
- src/CMakeLists.txt
- Update dependencies
- Fixed the python requirement checker to not use the deprecated `pkg_resources`.
- Disabled TESTS and BENCHMARKS for linux ci, i was not able to fix the `maybe_unused, this is an C++17 extension` warning - with the Clang compiler. 
- \+ some other smaller tweaks
> [ci|dep] Fix ci & update dependencies

- documentation/source/development/reference/octree-file-format.rst
I added [ImHex](https://imhex.werwolv.net/) pattern, which would make analysing, debugging or validating the binary files, much easier.
And a forth format idea, which uses bytes, but could use a compression algorithm like zip by default. To compare the 4th against the other we need some example files as i can not estimate the file size and/ or the performance gain by dropping the bit operations.
> Add hex pattern to octree format and add forth format idea

- .github/workflows/build.yml
- cmake/dependencies.cmake
- example/CMakeLists.txt
> [ci] Fix Windows Clang build

- .github/workflows/build.yml
- .github/workflows/static_analysis_clang_tidy.yml
- .github/workflows/static_analysis_cppcheck.yaml
Originally I thought I should cache the CMake build files as well, but this turns out to be a little more complex than I thought. For example, if any of the CMakeLists.txt anywhere in `src` would be updated, I would have to clear the cache. We can do this, but for now the easy solution is just to regenerate CMake build files every run.
The biggest open problem right now is that Linux CI does not cache Vulkan SDK for whatever reason. I will try to come up with a minimal example that works, maybe I can learn from that.
The "Post Lookup Vulkan SDK in cache" step says:
```
Post job cleanup.
/usr/bin/docker exec  5c344ee47a419455a5fafd506a0141655dc1e66c31424fbf0ddb5781fdf620e2 sh -c "cat /etc/*release | grep ^ID"
Warning: Path Validation Error: Path(s) specified in the action for caching …
```
> [ci] Cache Vulkan SDK download

- CMakeLists.txt
- dependencies.cmake
> [cmake] Put dependencies.cmake into root folder instead of extra subfolder

- .github/workflows/build.yml
- .github/workflows/static_analysis_clang_tidy.yml
- .github/workflows/static_analysis_cppcheck.yaml
* Cache the entire CMake build folder in Github actions cache (use checksum of all CMake files as key).
* Apply this to build and to static code analysis.
* Do not specify restore keys for caches.
This helps to drastically reduce build time (previously like 10 min)
> [ci] Cache CMake build folders

- dependencies.cmake
I want to print this file in the new docs, so I added some comments ~~and removed the Vulkan headers which are not required~~.
EDIT: The Vulkan headers are very much required. Just downloading the Vulkan SDK is not enough.
> [cmake] Improve CMake dependencies file

- .github/workflows/build.yml
- .github/workflows/build_documentation.yml
- .github/workflows/release.yml
- .github/workflows/static_analysis.yml
> [ci] Reorganize artifact names and sort in nightly release
